# Generated by Django 4.1.7 on 2023-04-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(default=None, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('had_pet', models.BooleanField(default=False)),
                ('can_pick_up', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.adoptionpost')),
                ('requested_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
        ),
    ]
