# Generated by Django 4.1.7 on 2023-04-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('other', 'Other')], max_length=10)),
                ('pet_breed', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_description', models.TextField(blank=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='static/img/pet')),
                ('pet_vaccinated', models.BooleanField(blank=True, null=True)),
                ('pet_colour', models.CharField(blank=True, max_length=20, null=True)),
                ('pet_gender', models.CharField(max_length=20)),
                ('pet_location', models.CharField(max_length=255)),
                ('pet_mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_age', models.IntegerField(blank=True, null=True)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('other', 'Other')], max_length=10)),
                ('pet_breed', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_description', models.TextField(blank=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='static/img/pet')),
                ('pet_vaccinated', models.BooleanField(blank=True, null=True)),
                ('pet_colour', models.CharField(blank=True, max_length=20, null=True)),
                ('pet_gender', models.CharField(max_length=20)),
                ('pet_location', models.CharField(max_length=255)),
                ('pet_mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_age', models.IntegerField(blank=True, null=True)),
                ('pet_food', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_behaviour', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_physicalcondition', models.CharField(blank=True, max_length=255, null=True)),
                ('pet_availability', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
