# Generated by Django 4.1.7 on 2023-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/pet'),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/pet'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
