# Generated by Django 4.1.7 on 2023-04-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_id_alter_customuser_email'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpet',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
        ),
    ]
