# Generated by Django 4.1.7 on 2023-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionpet',
            name='pet_age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='missingpet',
            name='pet_age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
