# Generated by Django 4.1.7 on 2023-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_adoptionpet_pet_age_alter_missingpet_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpet',
            name='accessories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='date_missing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='rewards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='still_missing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adoptionpet',
            name='pet_age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='missingpet',
            name='pet_age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
