# Generated by Django 4.1.7 on 2023-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_adoptionpet_user_missingpet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpet',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
