# Generated by Django 4.1.7 on 2023-04-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_missingpet_accessories_missingpet_date_missing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingpet',
            old_name='accessories',
            new_name='pet_accessories',
        ),
        migrations.RenameField(
            model_name='missingpet',
            old_name='date_missing',
            new_name='pet_date_missing',
        ),
        migrations.RenameField(
            model_name='missingpet',
            old_name='last_seen_location',
            new_name='pet_last_seen_location',
        ),
        migrations.RenameField(
            model_name='missingpet',
            old_name='rewards',
            new_name='pet_rewards',
        ),
        migrations.RenameField(
            model_name='missingpet',
            old_name='still_missing',
            new_name='pet_still_missing',
        ),
    ]
