# Generated by Django 4.1.7 on 2023-04-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_accessories_missingpet_pet_accessories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingpet',
            old_name='pet_date_missing',
            new_name='pet_datemissing',
        ),
    ]
